### ISSUE TITLE
integration into mainline

### ISSUE THREAD

**Issue by mteichtahl** [bitfocus/companion-module-tplink-kasasmartplug#4]
Hi team. you have saved me hours of needing to write my own module. thank you

I noticed that your good work has not yet been integrated in the mainline. Do you have an ETA ?

**Comment by McHauge** [comment]
@mteichtahl Hi, well it's included into the beta's as of yesterday I think. therefor it's already gonna be included in the next major release unless something goes wrong. But to give a time frame of when the next release will be is difficult. My best guess would be 3-6 months unless there comes a "module only" update in order to bring new and updated modules out to the public.

currently, companion doesn't support dynamically updating modules, but I'm pretty sure that will become a part of V3 when that comes around. so, for now, we are locked at using precompiled modules, in semi-regular releases. Hope it helps.

**Comment by mteichtahl** [comment]
thank you. it sure does thank you. 

on another note - would you be open to a PR to support the KP303 ? this would require assignment of the ports in the UI

**Comment by McHauge** [comment]
I don't think we would be opposed to it, but it might make sense to make the unit to be controlled selectable in the config page. So that you will only get the ID when using devices that need it.

But feel free to make a pull request and then we can take a look at it.

**Comment by mteichtahl** [comment]
Agreed.

 

Ill take a stab and raise a PR
